version: '3.9'

services:
  database:
    container_name: database
    image: postgres:latest
    env_file:
      - ./backend/.env
    ports:
      - 5050:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U theus -d filerequest"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - filerequest:/var/lib/postgresql/data
    
  migrations:
    container_name: migrations
    build: ./backend
    env_file:
      - ./backend/.env
    command:
      bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; python manage.py migrate'
    volumes:
      - .:/code
    depends_on:
      - database

  backend:
    container_name: backend
    build: ./backend
    env_file:
      - ./backend/.env
    command:
      bash -c 'while !</dev/tcp/database/5432; do sleep 1; done; python manage.py runserver 0.0.0.0:8000'
    volumes:
      - .:/code
    stdin_open: true 
    tty: true
    ports:
      - 8000:8000
    depends_on:
      - database
      - migrations

  # frontend:
  #   container_name: frontend
    
volumes:
  filerequest:
    external: true