# Generated by Django 4.1.3 on 2022-11-22 15:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Débito", "Debito"),
                            ("Boleto", "Boleto"),
                            ("Financiamento", "Financiamento"),
                            ("Crédito", "Credito"),
                            ("Recebimento Empréstimo", "Recebimento Emprestimo"),
                            ("Vendas", "Vendas"),
                            ("Recebimento TED", "Recebimento Ted"),
                            ("Recebimento DOC", "Recebimento Doc"),
                            ("Aluguel", "Aluguel"),
                        ],
                        max_length=50,
                    ),
                ),
                ("date", models.DateField()),
                ("value", models.FloatField()),
                ("cpf", models.CharField(max_length=50)),
                ("card_number", models.CharField(max_length=50)),
                ("hour", models.TimeField()),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="stores.store",
                    ),
                ),
            ],
        ),
    ]
